### ISSUE TITLE
Unable to open new .dvscene files

### ISSUE THREAD

**Issue by Ashrindy** [ik-01/DiEventRangers#1]
Hi!
I am in love with this template, it's very epic (would be even cooler as a C# library though). Though I want to edit the newest Sonic Frontiers Update 3 Boss Cutscenes, but it seems like there are some new elements that aren't implemented in this template. Would it be possible to update?
Huge thanks.

**Comment by Ashrindy** [comment]
Forgot to add this,
![obrazek](https://github.com/ik-01/DiEventRangers/assets/47925123/1b3f94d9-a1d6-4d60-bdb0-869083a64b67)
This is an example of it, this happens with all of the new boss cutscene files, this one is bo6165.dvscene.

**Comment by ik-01** [comment]
I figured out that Camera Node wasn't properly mapped.
Recent commit should fix this issue
![image](https://github.com/ik-01/DiEventRangers/assets/117114145/7ec4ae79-0cfd-4992-935f-bbc9f95462ef)

**Comment by Ashrindy** [comment]
Hello, and thanks again for the fix!
Though it seems like the issue is still present in some of the new custcene.
The only one I've found so far, is ev1770_mov.
![obrazek](https://github.com/ik-01/DiEventRangers/assets/47925123/5ea501d2-429a-4eb5-99ad-09eb2e93d892)
Would be happy for another fix!
